function [STAT1,STAT2]=fifthExperiment(alph,m,shuff,nTest,nroEpoch,XX,test)
% experiment p different than q
% each dimension is considered with a rbf kernel with its own
% kernel parameter
% input :
% 
% %test level
% alph=0.5;
% 
% %number of samples
% m=25;
% 
% %number of shuffles for boostrap
% shuff=300;
% 
% %number of tests
% nTest=100;
%
% %number of epochs
% nroEpoch=30;
%
% %crisp dataset
% XX

result=zeros(nTest,1);

%number of epochs for statistics


addpath ./kernels

%variables with final statistics
STAT1=zeros(nroEpoch,1);
STAT2=zeros(nroEpoch,1);

for epoch= 1:nroEpoch
    % kernel on fuzzy sets
    %----------------------
    for i=1:nTest
         % Testing samples from two different distributions
        if test==1
            %randomly choose 100 pairs of m samples class 1 and m samples class -1
            %chose the indices
            ind1=randsample(201,m);
            ind2=randsample(202:286,m);
        
        % Testing samples from the same  distribution
        else
            idClass=randi(2,1);
            if idClass==2
                %randomly choose 100 pairs of m samples class 1
                ind1=randsample(201,m);
                % and again another 100 pairs of m samples class 1
                ind2=randsample(201,m);
                
            else
                %randomly choose 100 pairs of m samples class -1
                ind1=randsample(202:286,m);
                % and again another 100 pairs of m samples class -1
                ind2=randsample(202:286,m);
            end            
        end
        %MMD for fuzzy kernels
        
        % testing the null hipotehsis that both samples were generated by the same
        % distribution
        
        %computing RBF kernel parameter with the median heuristic of the agregate
        %sample
        
        %XX
        %---------------------------------------------
        K=0;
        for j=2:10
            [lambda, ~ ,~]=computeLambda(XX(ind1,j),XX(ind2,j));
            K=K+RBF_kernel(XX(ind1,j),XX(ind1,j),1/lambda);
        end
                
        %YY
        %---------------------------------------------
        L=0;
        for j=2:10
            [lambda, ~ ,~]=computeLambda(XX(ind1,j),XX(ind2,j));
            L=L+RBF_kernel(XX(ind2,j),XX(ind2,j),1/lambda);
        end
                
        %XY
        %---------------------------------------------
        KL=0;
        for j=2:10
            [lambda, ~ ,~]=computeLambda(XX(ind1,j),XX(ind2,j));
            KL=KL+RBF_kernel(XX(ind1,j),XX(ind2,j),1/lambda);
        end
        
        %        
        %MMD statistic. Here we use biased
        %v-statistic. NOTE: this is m * MMD_b
        %testStat1(i) = 1/(m*(m-1)) * sum(sum(K + L - KL - KL'));
        %or
        testStat(i) = 1/m * sum(sum(K + L - KL - KL'));
                
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        result(i)=testMMD(K, L, KL,shuff, alph,testStat(i));
        
               
end
%     disp('mean test statistic 1');
%     mean(testStat);
%    disp('rate accepted p=q');
    STAT1(epoch)=length(result(find(result==1)));
%    disp('rate rejected p~= q');
    STAT2(epoch)=length(result(find(result==0)));
    result=zeros(nTest,1);
    
end
% disp('final results')
% disp('mean rate accepted')
% STAT1=mean(STAT1)
% disp('mean rate rejected')
% STAT2=mean(STAT2)
