function [STAT1,STAT2]=seventhExperiment(alph,m,shuff,nTest,nroEpoch,XX,test)
% two sample kernel fuzzy test
%  linear kernel over the crisp version of the fuzzy dataset
% input :
% 
% %test level
% alph=0.5;
% 
% %number of samples
% m=25;
% 
% %number of shuffles for boostrap
% shuff=300;
% 
% %number of tests
% nTest=100;
%
% %number of epochs
% nroEpoch=30;
%
% %crisp dataset
% XX

result=zeros(nTest,1);

%number of epochs for statistics


addpath ./kernels

%variables with final statistics
STAT1=zeros(nroEpoch,1);
STAT2=zeros(nroEpoch,1);

for epoch= 1:nroEpoch
    for i=1:nTest        %cho
         % Testing samples from two different distributions
        if test==1
            %randomly choose 100 pairs of m samples class 1 and m samples class -1
            %chose the indices
            ind1=randsample(201,m);
            ind2=randsample(202:286,m);
        
        % Testing samples from the same  distribution
        else
            idClass=randi(2,1);
            if idClass==2
                %randomly choose 100 pairs of m samples class 1
                ind1=randsample(201,m);
                % and again another 100 pairs of m samples class 1
                ind2=randsample(201,m);
                
            else
                %randomly choose 100 pairs of m samples class -1
                ind1=randsample(202:286,m);
                % and again another 100 pairs of m samples class -1
                ind2=randsample(202:286,m);
            end            
        end
        %MMD for fuzzy kernels
        
        % testing the null hipotehsis that both samples were generated by the same
        % distribution
        
        
        %---------------------------------------------
        K=linearKernel(XX(ind1,2:10),XX(ind1,2:10));
        
        %YY
        %---------------------------------------------
        L=linearKernel(XX(ind2,2:10),XX(ind2,2:10));
        
        %XY
        %---------------------------------------------
        KL=linearKernel(XX(ind1,2:10),XX(ind2,2:10));
        
        %MMD statistic. Here we use biased
        %v-statistic. NOTE: this is m * MMD_b
        %testStat1(i) = 1/(m*(m-1)) * sum(sum(K + L - KL - KL'));
        %or
        testStat(i) = 1/m * sum(sum(K + L - KL - KL'));
        
        
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        result(i)=testMMD(K, L, KL,shuff, alph,testStat(i));
        
        
end
%     disp('mean test statistic 1');
%     mean(testStat);
%    disp('rate accepted p=q');
    STAT1(epoch)=length(result(find(result==1)));
%    disp('rate rejected p~= q');
    STAT2(epoch)=length(result(find(result==0)));
    result=zeros(nTest,1);
    
end
% disp('final results')
% disp('mean rate accepted')
% STAT1=mean(STAT1)
% disp('mean rate rejected')
% STAT2=mean(STAT2)
